export const commands = {
    START:          'start',
    MIRRORTAR:      'mirrorTarxx|mtxx',
    MIRROR:         'mirrorxx|mxx',
    MIRROR_STATUS:  'mirrorStatusxx|msxx',
    LIST:           'listxx|lxx',
    GET_FOLDER:     'getFolderxx|gfxx',
    CANCEL_MIRROR:  'cancelMirrorx|cm',
    CANCEL_ALL:     'cancelAllx|ca',
    STATS:          'stats',
    GET_LINK:       'getLinkxx|glxx',
    CLONE:          'clonexx|cxx',
    ID:             'id',
    MF:             'mf',
    TAR:            'tar|t',
    UNZIP_MIRROR:   'unzipMirrorxx|umxx',
    COUT:           'count|cnt',
    HELP:           'helpxx|hx',
    AUTHORIZE:      'authorizexx|axx',
    UNAUTHORIZE:    'unauthorizexx|uaxx',
    RESTART:        'restart|r'
};

export const commandsAfter: any = {
    START:          '$',
    MIRRORTAR:      '($| (.+))',
    MIRROR:         '($| (.+))',
    MIRROR_STATUS:  '$',
    LIST:           ' (.+)',
    GET_FOLDER:     '$',
    CANCEL_MIRROR:  '($| (.+))',
    CANCEL_ALL:     '$',
    STATS:          '$',
    GET_LINK:       ' (.+)',
    CLONE:          ' (.+)',
    ID:             '$',
    MF:             '$',
    TAR:            ' (.+)',
    UNZIP_MIRROR:   ' (.+)',
    COUT:           ' (.+)',
    HELP:           '$',
    AUTHORIZE:      '$',
    UNAUTHORIZE:    '$',
    RESTART:        '$'
};